server:
  port: 8091
  servlet:
    context-path: /api/
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/fantasyListBuilder_test?createDatabaseIfNotExist=true
    username: root
    password: admin

logging:
  file:
    name: listBuilderTest.logs/logfile.log
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"